In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("ecommerce_sales_analytics_5000.csv")
df.sample()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
2793,12794,8/25/2029,1293,Clothing,North,2,60.69,0.19,Card,7,4.0,98.32

In [ ]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [ ]:
df.shape

(5000, 12)

In [ ]:
df.dtypes

order_id              int64
order_date           object
customer_id           int64
product_category     object
region               object
quantity              int64
unit_price          float64
discount            float64
payment_method       object
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [ ]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [ ]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

In [ ]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [ ]:
df["customer_rating"].mean()

np.float64(2.9739800000000005)

In [ ]:
df["unit_price"].max()

599.96

In [ ]:
df["unit_price"].min()

15.15

In [ ]:
df["delivery_days"].min()

1

In [ ]:
df["delivery_days"].max()

11

In [ ]:
df[['order_id',"customer_id","quantity","customer_rating"]].head()

   order_id  customer_id  quantity  customer_rating
0     10001         1102         7              4.7
1     10002         1435         7              3.9
2     10003         1860         3              2.5
3     10004         1270         5              1.6
4     10005         1106         5              4.9

In [ ]:
df.set_index("order_id",inplace=True)

In [ ]:
df.loc[14994]

order_date             9/3/2035
customer_id                1926
product_category    Electronics
region                     West
quantity                      1
unit_price               113.63
discount                   0.14
payment_method              COD
delivery_days                 4
customer_rating             1.0
revenue                   97.72
Name: 14994, dtype: object

In [ ]:
df.iloc[5]

order_date             1/6/2022
customer_id                1071
product_category    Electronics
region                     West
quantity                      2
unit_price               264.44
discount                    0.2
payment_method             Card
delivery_days                 3
customer_rating             3.3
revenue                   423.1
Name: 10006, dtype: object

In [ ]:
df.iloc[34:57]

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
order_id,,,,,,,,,,,
10035,2/4/2022,1021,Electronics,West,2,511.91,0.19,COD,9,1.5,829.29
10036,2/5/2022,1252,Electronics,West,4,375.27,0.02,COD,11,3.9,1471.06
10037,2/6/2022,1747,Clothing,South,3,186.01,0.13,Card,4,4.4,485.49
10038,2/7/2022,1856,Electronics,North,6,261.14,0.31,Card,6,3.5,1081.12
10039,2/8/2022,1560,Electronics,East,1,428.42,0.26,COD,10,1.7,317.03
10040,2/9/2022,1474,Home,North,7,584.36,0.11,Card,6,1.3,3640.56
10041,2/10/2022,1058,Electronics,North,4,537.49,0.33,Card,5,2.2,1440.47
10042,2/11/2022,1510,Home,West,4,215.32,0.03,Card,2,1.1,835.44
10043,2/12/2022,1681,Electronics,South,4,598.95,0.34,Card,7,4.4,1581.23
10044,2/13/2022,1475,Electronics,North,1,17.05,0.09,Card,1,3.8,15.52
10045,2/14/2022,1699,Home,East,3,31.16,0.00,Wallet,6,3.3,93.48
10046,2/15/2022,1975,Electronics,North,6,496.95,0.15,COD,5,4.6,2534.44
10047,2/16/2022,1782,Electronics,East,4,131.69,0.13,COD,5,1.4,458.28
10048,2/17/2022,1189,Clothing,West,1,50.55,0.19,Card,8,3.9,40.95
10049,2/18/2022,1957,Electronics,South,7,153.73,0.28,Card,9,1.6,774.80
10050,2/19/2022,1686,Home,North,2,264.27,0.29,Wallet,7,1.2,375.26
10051,2/20/2022,1957,Electronics,South,7,442.38,0.14,COD,10,1.5,2663.13
10052,2/21/2022,1562,Home,North,1,380.24,0.15,Card,8,4.8,323.20
10053,2/22/2022,1875,Beauty,East,1,154.01,0.05,Card,2,2.8,146.31
10054,2/23/2022,1566,Clothing,South,1,309.41,0.02,COD,2,1.2,303.22
10055,2/24/2022,1243,Beauty,North,4,556.84,0.22,Wallet,8,3.3,1737.34
10056,2/25/2022,1831,Clothing,West,1,491.78,0.02,Card,6,1.8,481.94
10057,2/26/2022,1504,Beauty,East,2,204.07,0.26,COD,8,1.0,302.02

In [ ]:
df[df["quantity"]<=1]

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
order_id,,,,,,,,,,,
10021,1/21/2022,1661,Home,West,1,48.12,0.16,COD,8,4.7,40.42
10024,1/24/2022,1343,Clothing,East,1,180.34,0.23,Card,7,3.1,138.86
10034,2/3/2022,1313,Home,North,1,274.96,0.27,Card,9,3.0,200.72
10039,2/8/2022,1560,Electronics,East,1,428.42,0.26,COD,10,1.7,317.03
10044,2/13/2022,1475,Electronics,North,1,17.05,0.09,Card,1,3.8,15.52
...,...,...,...,...,...,...,...,...,...,...,...
14983,8/23/2035,1745,Clothing,North,1,240.31,0.22,Wallet,11,3.1,187.44
14985,8/25/2035,1655,Clothing,West,1,237.76,0.23,COD,5,3.1,183.08
14989,8/29/2035,1449,Clothing,West,1,559.73,0.28,Card,1,4.4,403.01
14991,8/31/2035,1012,Home,East,1,265.48,0.32,Card,10,2.9,180.53
14994,9/3/2035,1926,Electronics,West,1,113.63,0.14,COD,4,1.0,97.72

In [ ]:
df[df["unit_price"]<=100]

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
order_id,,,,,,,,,,,
10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
10021,1/21/2022,1661,Home,West,1,48.12,0.16,COD,8,4.7,40.42
10026,1/26/2022,1413,Electronics,South,7,25.73,0.22,Card,8,2.0,140.49
10033,2/2/2022,1459,Electronics,North,6,64.94,0.09,Wallet,9,3.5,354.57
10044,2/13/2022,1475,Electronics,North,1,17.05,0.09,Card,1,3.8,15.52
...,...,...,...,...,...,...,...,...,...,...,...
14980,8/20/2035,1656,Home,East,4,76.37,0.24,Card,4,3.7,232.16
14984,8/24/2035,1379,Home,South,2,48.35,0.04,COD,8,2.2,92.83
14987,8/27/2035,1187,Clothing,North,6,27.28,0.34,Wallet,7,3.2,108.03
14995,9/4/2035,1507,Home,South,6,25.85,0.12,Card,5,3.1,136.49
14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06

In [ ]:
df[
    ( (df["unit_price"]<=100) &
     (df["quantity"]>1) &
      ((df["product_category"]=="Clothing") |
       (df["product_category"]=="Home"))
      )]

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
order_id,,,,,,,,,,,
10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
10045,2/14/2022,1699,Home,East,3,31.16,0.00,Wallet,6,3.3,93.48
10060,3/1/2022,1818,Clothing,South,2,51.53,0.19,Wallet,11,4.8,83.48
10061,3/2/2022,1646,Clothing,North,5,35.57,0.06,Card,6,3.4,167.18
10066,3/7/2022,1387,Home,South,4,69.56,0.25,Wallet,1,3.1,208.68
...,...,...,...,...,...,...,...,...,...,...,...
14954,7/25/2035,1801,Clothing,South,3,41.22,0.15,Card,6,1.6,105.11
14980,8/20/2035,1656,Home,East,4,76.37,0.24,Card,4,3.7,232.16
14984,8/24/2035,1379,Home,South,2,48.35,0.04,COD,8,2.2,92.83
14987,8/27/2035,1187,Clothing,North,6,27.28,0.34,Wallet,7,3.2,108.03
14995,9/4/2035,1507,Home,South,6,25.85,0.12,Card,5,3.1,136.49

In [ ]:
df.sort_values("revenue",ascending=False)

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
order_id,,,,,,,,,,,
10810,3/20/2024,1890,Electronics,South,7,594.42,0.01,Card,4,4.9,4119.33
14884,5/16/2035,1146,Electronics,South,7,583.31,0.00,Card,5,4.4,4083.17
12215,1/24/2028,1113,Electronics,South,7,591.15,0.02,Wallet,1,3.2,4055.29
13102,6/29/2030,1699,Beauty,East,7,596.12,0.04,COD,6,3.0,4005.93
13687,2/4/2032,1831,Clothing,North,7,578.59,0.03,COD,8,1.6,3928.63
...,...,...,...,...,...,...,...,...,...,...,...
10377,1/12/2023,1232,Electronics,North,1,15.78,0.16,Wallet,10,4.8,13.26
14069,2/20/2033,1177,Clothing,South,1,19.41,0.32,Wallet,1,1.1,13.20
10071,3/12/2022,1776,Home,South,1,18.59,0.30,Card,1,1.8,13.01
10565,7/19/2023,1341,Clothing,North,1,19.74,0.35,COD,8,4.3,12.83
13644,12/23/2031,1435,Clothing,South,1,15.15,0.26,Card,5,3.5,11.21

In [ ]:
df.sort_values(
    ["product_category", "revenue"],
    ascending=[True, False]
)

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
order_id,,,,,,,,,,,
13102,6/29/2030,1699,Beauty,East,7,596.12,0.04,COD,6,3.0,4005.93
14306,10/15/2033,1283,Beauty,South,7,555.09,0.02,COD,11,4.9,3807.92
10370,1/5/2023,1303,Beauty,South,7,529.25,0.02,Card,7,1.3,3630.66
12364,6/21/2028,1270,Beauty,West,7,562.65,0.08,COD,11,2.6,3623.47
11681,8/8/2026,1193,Beauty,South,7,593.69,0.15,COD,8,1.7,3532.46
...,...,...,...,...,...,...,...,...,...,...,...
14694,11/7/2034,1876,Home,South,1,41.52,0.18,COD,10,4.5,34.05
11010,10/6/2024,1176,Home,East,1,37.78,0.26,Card,8,3.6,27.96
13008,3/27/2030,1451,Home,East,1,23.56,0.32,COD,1,1.2,16.02
10088,3/29/2022,1561,Home,West,1,20.90,0.31,COD,10,3.1,14.42
10071,3/12/2022,1776,Home,South,1,18.59,0.30,Card,1,1.8,13.01

In [ ]:
df["product_category"].unique()

array([7, 3, 5, 2, 6, 4, 1])

In [ ]:
df["quantity"].unique()

array([7, 3, 5, 2, 6, 4, 1])

In [ ]:
df["discount"].nunique()

36

In [ ]:
df["payment_method"].value_counts()

payment_method
Card      2270
COD       1774
Wallet     956
Name: count, dtype: int64

In [ ]:
df.groupby("product_category")["revenue"].sum()

product_category
Beauty          765860.88
Clothing       1531931.72
Electronics    1829899.22
Home            982083.92
Name: revenue, dtype: float64

In [ ]:
df.groupby("product_category")["customer_rating"].mean()

product_category
Beauty         3.008990
Clothing       3.005095
Electronics    2.951097
Home           2.940660
Name: customer_rating, dtype: float64

In [ ]:
df.groupby("region")["revenue"].sum()

region
East     1236044.23
North    1281508.45
South    1246640.90
West     1345582.16
Name: revenue, dtype: float64

In [ ]:
df.groupby("region")["delivery_days"].mean()

region
East     6.104319
North    6.118339
South    6.173013
West     6.082234
Name: delivery_days, dtype: float64

In [ ]:
df.groupby("region")["revenue"].agg(
    ["sum", "mean", "max", "min"]
)

               sum         mean      max    min
region
East    1236044.23  1007.371011  4005.93  14.43
North   1281508.45  1004.316967  3928.63  12.83
South   1246640.90  1031.987500  4119.33  11.21
West    1345582.16  1043.896168  3898.48  13.78

In [ ]:
df["Total_price"]= df["quantity"]*df["unit_price"]
df

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Total_price
order_id,,,,,,,,,,,,
10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55
10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18
10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84
10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35
10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35
...,...,...,...,...,...,...,...,...,...,...,...,...
14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74,743.48
14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47,1661.01
14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06,231.66
14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38,553.64
15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90,1621.06

In [ ]:
df[
    ( (df["Total_price"]<=100) &
     (df["quantity"]>1) &
      ((df["product_category"]=="Clothing") |
       (df["product_category"]=="Home"))
      )]

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Total_price
order_id,,,,,,,,,,,,
10045,2/14/2022,1699,Home,East,3,31.16,0.00,Wallet,6,3.3,93.48,93.48
10169,6/18/2022,1871,Clothing,North,2,17.40,0.16,Card,8,4.4,29.23,34.80
10236,8/24/2022,1230,Clothing,East,5,16.10,0.15,COD,9,2.6,68.42,80.50
10350,12/16/2022,1640,Clothing,East,3,27.54,0.23,Card,1,3.4,63.62,82.62
10478,4/23/2023,1348,Clothing,South,2,47.15,0.04,COD,8,3.1,90.53,94.30
10483,4/28/2023,1098,Clothing,North,2,19.24,0.00,Card,11,1.4,38.48,38.48
10540,6/24/2023,1320,Clothing,South,2,26.25,0.08,COD,7,1.3,48.30,52.50
10672,11/3/2023,1836,Clothing,North,2,20.59,0.26,Wallet,7,3.5,30.47,41.18
10755,1/25/2024,1738,Clothing,South,3,30.19,0.35,COD,6,2.0,58.87,90.57
10885,6/3/2024,1172,Clothing,West,4,21.80,0.29,Card,3,1.7,61.91,87.20
11062,11/27/2024,1094,Home,West,4,20.39,0.10,COD,6,2.1,73.40,81.56
11124,1/28/2025,1183,Home,West,2,30.20,0.25,Card,7,3.9,45.30,60.40
11243,5/27/2025,1014,Clothing,West,3,24.02,0.08,Card,11,2.3,66.30,72.06
11293,7/16/2025,1740,Clothing,West,2,28.93,0.33,COD,2,2.9,38.77,57.86
11312,8/4/2025,1136,Clothing,South,4,16.01,0.06,Card,9,3.7,60.20,64.04
11474,1/13/2026,1499,Clothing,South,4,20.00,0.31,Wallet,6,4.1,55.20,80.00
11483,1/22/2026,1156,Home,South,2,45.45,0.13,Wallet,1,1.6,79.08,90.90
11570,4/19/2026,1461,Home,North,2,38.36,0.34,Card,6,1.8,50.64,76.72
11846,1/20/2027,1026,Clothing,North,3,25.17,0.31,Card,9,4.3,52.10,75.51
11861,2/4/2027,1980,Home,North,2,24.88,0.18,COD,10,4.5,40.80,49.76
11905,3/20/2027,1490,Clothing,South,5,15.77,0.14,Card,4,5.0,67.81,78.85
12116,10/17/2027,1225,Home,North,2,39.14,0.25,COD,4,1.1,58.71,78.28
12125,10/26/2027,1574,Clothing,South,2,26.81,0.26,COD,5,5.0,39.68,53.62
12217,1/26/2028,1300,Clothing,West,3,31.96,0.11,COD,10,4.7,85.33,95.88
12297,4/15/2028,1454,Clothing,North,2,49.02,0.12,COD,3,2.3,86.28,98.04
12308,4/26/2028,1988,Clothing,West,2,18.48,0.23,COD,2,3.9,28.46,36.96
12354,6/11/2028,1481,Clothing,North,5,15.32,0.14,Card,5,1.3,65.88,76.60
12452,9/17/2028,1830,Home,West,3,17.35,0.00,COD,9,3.7,52.05,52.05
12734,6/26/2029,1932,Home,West,2,30.23,0.22,COD,8,3.6,47.16,60.46
12798,8/29/2029,1637,Clothing,West,4,15.18,0.03,Card,3,2.8,58.90,60.72
12800,8/31/2029,1307,Home,South,3,26.54,0.04,Card,8,3.4,76.44,79.62
12964,2/11/2030,1786,Home,West,2,34.47,0.11,COD,5,4.5,61.36,68.94
13055,5/13/2030,1969,Home,West,3,18.05,0.24,Wallet,1,2.3,41.15,54.15
13424,5/17/2031,1163,Clothing,West,3,15.83,0.07,Card,7,3.0,44.17,47.49
13624,12/3/2031,1237,Home,East,3,30.38,0.25,COD,3,2.3,68.36,91.14
13741,3/29/2032,1821,Home,West,5,18.47,0.00,COD,2,4.1,92.35,92.35
13922,9/26/2032,1874,Clothing,South,2,36.78,0.14,COD,2,3.6,63.26,73.56
13976,11/19/2032,1597,Clothing,West,2,19.50,0.34,Card,1,4.8,25.74,39.00
14392,1/9/2034,1430,Clothing,East,6,15.67,0.34,Wallet,5,2.8,62.05,94.02
14405,1/22/2034,1405,Clothing,East,2,17.08,0.34,Card,2,4.8,22.55,34.16
14407,1/24/2034,1532,Clothing,North,3,32.42,0.22,Card,10,3.0,75.86,97.26
14661,10/5/2034,1567,Clothing,North,2,48.28,0.24,Card,7,3.7,73.39,96.56
14825,3/18/2035,1976,Clothing,West,3,28.51,0.03,COD,9,2.5,82.96,85.53
14916,6/17/2035,1285,Clothing,North,3,20.82,0.13,COD,4,1.3,54.34,62.46
14925,6/26/2035,1112,Clothing,North,4,20.61,0.30,Wallet,9,2.3,57.71,82.44
14984,8/24/2035,1379,Home,South,2,48.35,0.04,COD,8,2.2,92.83,96.70

In [ ]:
df["rating_status"] = df["customer_rating"].apply(
    lambda x: "Good" if x >= 4 else "Needs Improvement"
)
df.head()

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Total_price,rating_status
order_id,,,,,,,,,,,,,
10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,Good
10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,Needs Improvement
10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,Needs Improvement
10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,Needs Improvement
10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,Good

In [ ]:
df["order_date"]=pd.to_datetime(df["order_date"])
df.head()

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Total_price,rating_status
order_id,,,,,,,,,,,,,
10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,Good
10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,Needs Improvement
10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,Needs Improvement
10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,Needs Improvement
10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,Good

In [ ]:
df["year"] = df["order_date"].dt.year

In [ ]:
df.tail()

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Total_price,rating_status,year
order_id,,,,,,,,,,,,,,
14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74,743.48,Needs Improvement,2035
14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47,1661.01,Needs Improvement,2035
14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06,231.66,Needs Improvement,2035
14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38,553.64,Needs Improvement,2035
15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90,1621.06,Needs Improvement,2035

In [ ]:
df["year"].unique()

array([2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032,
       2033, 2034, 2035], dtype=int32)

In [ ]:
df["month"] = df["order_date"].dt.month
df.tail()

,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Total_price,rating_status,year,month
order_id,,,,,,,,,,,,,,,
14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74,743.48,Needs Improvement,2035,9
14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47,1661.01,Needs Improvement,2035,9
14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06,231.66,Needs Improvement,2035,9
14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38,553.64,Needs Improvement,2035,9
15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90,1621.06,Needs Improvement,2035,9

In [ ]:
df.duplicated().sum()

np.int64(0)